language: python

python:
- '2.7'
- '3.3'
- pypy

env:
  - ELECTRUM_VERSION=1.9.8 ELECTRUM_MD5=e3918fec0254267f08e41a1fb8691382

install:
  - sudo apt-get install python-qt4
  - sudo pip install slowaes==0.1a1
  - sudo pip install https://download.electrum.org/Electrum-${ELECTRUM_VERSION}.tar.gz#md5=${ELECTRUM_MD5}

script: python test.py
